using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("HtmlElements-dotNet: WebDriver PageObject extension for .NET")]
[assembly: AssemblyCompanyAttribute("Yandex QATools")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2012 Yandex QATools and contributors")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]

